(lang dune 3.22)

(name myers_list)

(generate_opam_files true)

(homepage "https://github.com/Techirocat/Lib_MyersList")

(source
 (github Techirocat/Lib_MyersList))

(authors "Guilherme Guerreiro" "Miguel Alvito")

(maintainers "Techirocat" "m-alvito")

(documentation https://url/to/documentation)

(package
 (name myers_list)
 (synopsis "Random-Access Lists")
 (description "An OCaml library providing efficient Random-Access Lists based on Myers's approach. It offers a 
               collection of functional list data structures that combine O(1) cons/head/tail operations with 
               fast O(log n) random access.")
 (depends ocaml
    (alcotest :with-test))

(tags ("data-structures" "myers-list" "random-access-list" "functional-data-structures")))
