name: Deploy OCaml Docs

on:
  push:
    branches:
      - main
      - odoc

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    defaults:
      run:
        working-directory: ./myers_list

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Instalar dependências e Odoc
        run: |
          opam install . --deps-only --with-doc
          opam install odoc

      - name: Gerar Documentação
        run: opam exec -- dune build @doc

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./myers_list/_build/default/_doc/_html